### ISSUE TITLE
Problems to generate googleapis gRPC source code

### ISSUE THREAD

**Issue by jerrychang1243** [GoogleCloudPlatform/cpp-docs-samples#41] opened 2018-07-27 10:54 UTC
in googleapis/ 
$ make all

protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/ads/googleads/v0/resources/ad_group.proto
google/ads/googleads/v0/common/custom_parameter.proto:31:8: Option "php_metadata_namespace" unknown.
google/ads/googleads/v0/enums/ad_group_status.proto:29:8: Option "php_metadata_namespace" unknown.
google/ads/googleads/v0/enums/ad_group_type.proto:29:8: Option "php_metadata_namespace" unknown.
google/ads/googleads/v0/resources/ad_group.proto: Import "google/ads/googleads/v0/common/custom_parameter.proto" was not found or had errors.
google/ads/googleads/v0/resources/ad_group.proto: Import "google/ads/googleads/v0/enums/ad_group_status.proto" was not found or had errors.
google/ads/googleads/v0/resources/ad_group.proto: Import "google/ads/googleads/v0/enums/ad_group_type.proto" was not found or had errors.
google/ads/googleads/v0/resources/ad_group.proto:60:3: "enums.AdGroupStatusEnum.AdGroupStatus" is not defined.
google/ads/googleads/v0/resources/ad_group.proto:63:3: "enums.AdGroupTypeEnum.AdGroupType" is not defined.
google/ads/googleads/v0/resources/ad_group.proto:70:12: "common.CustomParameter" is not defined.
Makefile:44: recipe for target 'google/ads/googleads/v0/resources/ad_group.pb.cc' failed
make: *** [google/ads/googleads/v0/resources/ad_group.pb.cc] Error 1

how to fix it?

**Comment by coryan** [comment] 2018-07-27 14:12
Looks like you are using an old version of protoc. I cannot remember if the php stuff was introduced in 3.5 or 3.4, I would go with 3.5.

**Comment by jerrychang1243** [comment] 2018-07-30 12:02
@coryan 
My protoc version is 3.5.1

**Comment by coryan** [comment] 2018-08-23 21:58
Sorry for the delay, I was busy with my full-time job.  You are correct, googleapis does not compile with protobuf v3.5.1 or v3.5.2, which is the default version used by gRPC.  googleapis recently introduced proto files that use the `php_metadata_namespace`, for example here:

https://github.com/googleapis/googleapis/blob/288ebfec039030c7dd9de05b73879634b72e0dc4/google/ads/googleads/v0/enums/day_of_week.proto#L29

while support for that option was added to protobuf here:

https://github.com/protocolbuffers/protobuf/pull/4609

That pull request made it to protobuf-3.6.1.

We should change the documentation and code to require protobuf >= 3.6.1.

I am attaching a [Dockerfile](https://github.com/GoogleCloudPlatform/cpp-docs-samples/files/2316336/Dockerfile.txt) that can be used to reproduce the problem (with `--build-arg=PBVER=3.5.2`) and verify that it works with the newer version (with `--build-arg=PBVER=3.6.1`).

/cc: @SurferJeffAtGoogle

**Comment by tmatsuo** [comment] 2019-10-23 20:28
@jerrychang1243 I think we can close this issue, but feel free to reopen.

**Closed by tmatsuo** 2019-10-23 20:28 UTC
